= System Scope and Context
[[section-system-scope-and-context]]

ifndef::imagesdir[:imagesdir: ../images]


== Business Context

.These use cases revolve around the ((PC))s. They are called ((Operative))s here.
[plantuml,business-context-operatives,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

rectangle Users {
    Player as user << Human >>
    GM as gm << Human >>
}

rectangle TorganizedPlay {
    Judge as judge << Human >>
    Orga as orga << Human >>
    Admin as admin << Human >>
}

rectangle Operatives {
    usecase "Register Operative" as opreg
    usecase "List Operatives" as oplist
    usecase "List Operatives History" as ophistory
    usecase "Decomission Operative" as opretire
    usecase "Re-enlist Operative" as opreenlist

    usecase "Petition Operative" as oppetition
    usecase "Detain Operative" as opdetain
    usecase "Release Operative" as oprelease
}

user --> opreg
user --> oplist
user --> ophistory : only owned
user --> opretire : only owned
user --> oppetition
gm --> oplist
gm --> ophistory : only on table
gm --> oppetition
oplist <-- judge
ophistory <-- judge
opretire <-- judge
opreenlist <-- judge
opdetain <-- judge
oprelease <-- judge
oplist <-- orga
ophistory <-- orga
opretire <-- orga
opreenlist <-- orga
oppetition <-- orga
oprelease <-- orga
opreg <-- admin
oplist <-- admin
ophistory <-- admin
opretire <-- admin
opreenlist <-- admin
opdetain <-- admin
oprelease <-- admin




@enduml
....

.These use cases revolve around the session (((Session)) management of the games and the shared campaign (((Shared Campaign))) management.
[plantuml,business-context-gaming,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player as user << Human >>
GM as gm << Human >>

rectangle Gaming {
    usecase "Create new Mission" as mcreate

    usecase "Register new Mission" as mreg
    usecase "Score a played Mission" as mscore

    usecase "List open Missions" as mlist
    usecase "Apply for Mission" as mapply
    usecase "Accept for Mission" as maccept
    usecase "Remove Operative from Mission" as mremove

    usecase "Petition a mission" as mpetition
    usecase "Block a mission" as mblock
    usecase "Unblock a mission" as munblock
    usecase "Delete a mission" as mdelete
}

rectangle TorganizedPlay {
    Judge as judge << Human >>
    Orga as orga << Human >>
    Admin as admin << Human >>
}

user --> mlist
user --> mapply : self
user --> mremove : self
user --> mpetition
gm --> mcreate : special mission
gm --> mreg
gm --> mscore
gm --> mlist
gm --> maccept : owned
gm --> mremove : owned
gm --> mpetition

mlist <-- judge
mremove <-- judge
mblock <-- judge
munblock <-- judge
mdelete <-- judge
mcreate <-- orga
mlist <-- orga
mremove <-- orga
mblock <-- orga
munblock <-- orga
mpetition <-- orga
mcreate <-- admin
mreg <-- admin
mscore <-- admin
mlist <-- admin
mapply <-- admin
maccept <-- admin
mremove <-- admin
mpetition <-- admin
mblock <-- admin
munblock <-- admin
mremove <-- admin
mdelete <-- admin

@enduml
....


.The management and use of new ((Threat))s.
[plantuml,business-context-threats,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player as user << Human >>
GM as gm << Human >>

rectangle API {
    :Foundry VTT: as foundryVTT << System >>
    :Torg-Codex: as torgCodex << System >>
}

rectangle Threats {
    usecase "Create a new threat" as cthreat
    usecase "Remove a threat" as cremove

    usecase "Petition threat" as pthreat
    usecase "Block threat" as cblock
    usecase "Unblock threat" as cunblock

    usecase "List existing threats" as clist
    usecase "Download a threat" as cdown
}

rectangle TorganizedPlay {
    Judge as judge << Human >>
    Orga as orga << Human >>
    Admin as admin << Human >>
}

user --> clist
user --> cdown
user --> pthreat

gm --> cthreat
gm --> cremove : owned
gm --> clist
gm --> cblock : owned
gm --> cunblock : self blocked
gm --> cdown
gm --> pthreat
cthreat <-- orga
clist <-- orga
cdown <-- orga
cblock <-- orga
cunblock <-- orga
pthreat <-- orga
cblock <-- judge
cunblock <-- judge
cremove <-- judge
cthreat <-- admin
cremove <-- admin
clist <-- admin
cdown <-- admin
cblock <-- admin
cunblock <-- admin

foundryVTT --> clist
foundryVTT --> cdown
foundryVTT --> pthreat
torgCodex --> clist
torgCodex --> cdown
torgCodex --> pthreat

@enduml
....


.The integrated ((torg-codex)).
[plantuml,business-context-codex,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player as user << Human >>
GM as gm << Human >>

rectangle TorganizedPlay {
    Judge as judge << Human >>
    Orga as orga << Human >>
    Admin as admin << Human >>
}

rectangle Codex {
    usecase "All of torg-codex" as codex
}

user --> codex

@enduml
....


.Player management.
[plantuml,business-context-user,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player << Human >> as user
GM << Human >> as gm

rectangle DCIS {
    :dcis-users: as dcisUsers << System >>
    :dcis-gaming: as dcisGaming << System >>
    :dcis-threats: as dcisThreats << System >>
    :dcis-operatives: as dcisOperatives << System >>
    :torg-codex: as torgCodex << System >>
}

rectangle Player {
    usecase "List users" as ulist
    usecase "List user logfile" as ulogfile

    usecase "Create new logfile entry" as ulog

    usecase "Petition user" as upetition
    usecase "Detain user" as udetain
    usecase "Petition Detainment" as udetainpetition
    usecase "Release user" as urelease

    usecase "Ban user" as uban
    usecase "Petition Ban" as ubanpetition
    usecase "Unban user" as uunban
}

rectangle TorganizedPlay {
    Judge << Human >> as judge
    Orga << Human >> as orga
    Admin << Human >> as admin
}

user --> ulist
user --> ulogfile
user --> upetition
user --> udetainpetition
user --> ubanpetition
gm --> ulist
gm --> upetition
ulist <-- judge
ulogfile <-- judge
uban <-- judge
uunban <-- judge
udetain <-- judge
urelease <-- judge
ulist <-- orga
ulogfile <-- orga
udetain <-- orga
urelease <-- orga
ulist <-- admin
ulogfile <-- admin
uban <-- admin
uunban <-- admin
udetain <-- admin
urelease <-- admin

dcisUsers --> ulog
dcisGaming --> ulog
dcisThreats --> ulog
dcisOperatives --> ulog
torgCodex --> ulog

@enduml
....


<<<
== Technical Context

.The technical context of the DCIS.
[plantuml,technical-context,svg]
....
@startuml
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

:Player: << Human >>
:GM: << Human >>
[k8s ingress]
:Judge: << Human >>
:Orga: << Human >>
:Admin: << Human >>

component "k8s ingress" {
    portin HTTP as HTTPingressIn

    component "ingress" as HTTPingress

    HTTPingressIn -- HTTPingress
}

[FoundryVTT]
[SSO]

together{
    [dcis-gaming]
    [torg-codex]
    [dcis-threats]
    [dcis-operatives]
    together {
        [dcis-users]
        [mail]
        [discord]
    }
}
[dcis-commons]

component dcis-gaming {
    portin HTTP as HTTPgaming
    portout AMQP as AMQPgaming

    component "torganized-play-gaming" as DCISgaming
    database "PostgreSQL" as gamingDB

    HTTPgaming -- DCISgaming
    AMQPgaming -- DCISgaming
    DCISgaming -- gamingDB
}

component torg-codex {
    portin HTTP as HTTPcodex
    portout AMQP as AMQPcodex

    component "torg-codex" as DCIScodex
    database "MongoDB" as codexDB

    HTTPcodex -- DCIScodex
    AMQPcodex -- DCIScodex
    DCIScodex -- codexDB
}

component dcis-threats {
    portin HTTP as HTTPthreats
    portout AMQP as AMQPthreats

    component "torganized-play-threats" as DCISthreats
    database "PostgreSQL" as threatsDB

    HTTPthreats -- DCISthreats
    AMQPthreats -- DCISthreats
    DCISthreats -- threatsDB
}

[broker-broker]
component "broker-broker" {
    portin AMQP as AMQPbroker

    component "broker-broker" as DCISbroker

    AMQPbroker -- DCISbroker
}

component dcis-operatives {
    portin HTTP as HTTPoperatives
    portout AMQP as AMQPoperatives

    component "torganized-play-operatives" as DCISoperatives
    database "PostgreSQL" as operativesDB

    HTTPoperatives -- DCISoperatives
    AMQPoperatives -- DCISoperatives
    DCISoperatives -- operativesDB
}

component dcis-users {
    portin HTTP as HTTPusers
    portout AMQP as AMQPusers

    component "torganized-play-users" as DCISusers
    database "PostgreSQL" as usersDB

    HTTPusers -- DCISusers
    AMQPusers -- DCISusers
    DCISusers -- usersDB
}

component dcis-commons {
    portin HTTP as HTTPcommons

    component "torganized-play-commons" as DCIScommons

    HTTPcommons -- DCIScommons
}



:Player: .d.> HTTPingressIn
:GM: .d.> HTTPingressIn
:Judge: .d.> HTTPingressIn
:Orga: .d.> HTTPingressIn
:Admin: .d.> HTTPingressIn

FoundryVTT .d.> HTTPingressIn

DCISgaming ..> SSO
DCIScodex ..> SSO
DCISthreats ..> SSO
DCISoperatives ..> SSO
DCISusers ..> SSO

HTTPingress .d.> HTTPgaming : use
HTTPingress .d.> HTTPcodex : use
HTTPingress .d.> HTTPthreats : use
HTTPingress .d.> HTTPoperatives : use
HTTPingress .d.> HTTPusers : use
HTTPingress .d.> HTTPcommons : use

DCISusers ..> mail : use
DCISusers ..> discord : use

AMQPbroker <.u.> AMQPgaming : use
AMQPbroker <.u.> AMQPcodex : use
AMQPbroker <.u.> AMQPthreats : use
AMQPbroker <.u.> AMQPoperatives : use
AMQPbroker <.u.> AMQPusers : use
@enduml
....

**<Mapping Input/Output to Channels>**
