[[section-solution-strategy]]
= Solution Strategy

ifndef::imagesdir[:imagesdir: ../images]

== Modularization

Every distinct aspect is modelled into a single vertical.
The current verticals are:

* xref:05_building_block_view/level_1/dcis-users.adoc[]
* xref:05_building_block_view/level_1/dcis-arbitration.adoc[]
* xref:05_building_block_view/level_1/dcis-operatives.adoc[]
* xref:05_building_block_view/level_1/dcis-gaming.adoc[]
* xref:05_building_block_view/level_1/dcis-threats.adoc[]
* xref:05_building_block_view/level_1/torg-codex.adoc[]
* xref:05_building_block_view/level_1/dcis-commons.adoc[]
* xref:05_building_block_view/level_1/dcis-discord.adoc[]


== Single Sign On

The system holds no authentication data.
It will be connected via OpenIDConnect to external identity providers (like keycloak).
The users are specified via their external user.
Internally they get an UUID which maps to the (Issuer, User) tuple of the external provider.


== Frontend and backend integration

The systems use frontend integration methods for the UI.

Needed communication between the backends (data synchronization, event distribution) are handled via a messaging infrastructure.
The broker used will be a rabbitMQ handling AMQP queues and topics.
