= Cross-cutting Concepts
[[section-concepts]]

ifndef::imagesdir[:imagesdir: ../images]


== Self Contained Systems

The system architecture is a microservice based approach following the self-contained system as specified by
cite:[scs].


== Observability

=== Logging

The system will log json events.


=== Monitoring

The microservices will provide prometheus metrics to be harvested.


=== Alerting

Alerting is handled via prometheus and defined using the metrics provided by the systems.


=== Reporting

Currently, there are no plans for a structured reporting.


== Role Based Access

The system uses a RBAC approach to the system access control.
The following roles are defined:

.Roles of the system
[cols="<.<4,<.<4,<.<12a",option="header",frame="topbot",grid="rows"]
|===
| Role | Cardinality | Description

| Player
| Everyone on the system
| This is the basic role when logged in.
Access is granted to all public data.

| GM
| Players who are also GMs
| GMs can manage game sessions and see data of operatives (including their history) when being registered for or applying to a game session.

| Third Party Systems
| API using systems
| Third Party Systems (like ((FoundryVTT))) normally use the privileges of the person using them.

| Orga
| Torganized Play Organization
| The Orga organizes the whole system.
It manages the storyline and handles the mission data.
A person with orga access has the ability to see almost any data and block/unblock most data.

| Judge
| Torganized Play Organization
| A Judge is an arbiter.
If there are conflicts that can't be resolved between the parties themself, a judge may be called to decide.
A judge has access to all data and can block, unblock and delete almost any data to execute on their decision.

| Admin
| Torganized Play Organization
| Full access. Nothing is hidden or impossible for admin level.
|===


== Data Protection

Most of the data is user generated and heavily linked to the person who created it.
Therefore there must be provisions to protect the rights of the users.

=== Access Control

The user needs to log in to do most actions.
An external Identity Provider is used for this.
The external provider and the user there are combined to a tupel (Issuer, User) and an UUID will be generated.
This UUID is used within all systems to identify the owner of certain data objects.
The `DCIS Users` vertical is used to de-pseudominize the data to the (Issuer, User) tupel.


**Retention Time:** The tupel and the UUID is the account.
It will be deleted three years after closing of the account.
The Account will be *blocked* for everyone but Judges and Admins immediately after closing the account.

=== Auditing

There is an audit log of all user actions and information related to the user within the `DCIS Users` vertical.
The user may check this logfile via Web UI.

**Retention Time:** The audit log is preserved for the whole existence of an account.
It will be deleted with the removal of the account.

=== Public Data

All data entered into the system is to be considered public data.
Exemptions are listed in section <<section-concepts-private-data>>.


[[section-concepts-private-data]]
=== Private Data

. Credentials (API Key) to DriveThrough may be stored to use several automation functions.
Since the API key needs to be sent in unencrypted versions to the backend services used, they can't be encrypted.
They will not be displayed to users, gm, admins, orga or judges.

. API Keys for third party systems.
They are generated by users to enable third party systems to use the DCIS apis.
They are visible to and manageable by judges and admins.

. Fields marked as "internal only" or "Notes to".
They describe who has access to that data and who hasn't.


[[section-user-created-content]]
=== User created content
Content created by the user will not be deleted when user account data is deleted or blocked.

It will be unlinked from the account and ownership transferred to the Torganized Play Organisation.
If the creator does not consent to that, it is his responsibility to delete the data before closing the account.
An option to delete/block all user created data will be given when closing the account.

In case, the created data also belongs to other users accounts (like notes for missions), the data ownership is shared and closing an account will transfer it to the other party involved.


[[section-concepts-retention-period]]
=== Retention Period

All data is linked to an account.

The personal data will be blocked at the moment the account is closed.
The data will be deleted **three years** after closing the account.

If there is a lawsuit (ongoing or up-coming) or a written agreement by the owner, the data will not be deleted.