@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

together {
  Player << Human >> as user
  GM << Human >> as gm
  :Foundry VTT: as foundry << System >>
  :Discord: as discord << System >>

  :Virtual API: as api << Virtual >>
}

together {
  Judge << Human >> as judge
  Orga << Human >> as orga
  Admin << Human >> as admin
}

user <|-.- gm : is a
user <|-.- orga : is a

orga <|-.- judge : is a
orga <|-.- admin : is a

:DCIS Discord: as dcisDiscord << System >>
:DCIS Gaming: as dcisGaming << System >>
:DCIS Users: as dcisUsers << System >>


rectangle :dcis-operatives: as operatives << System >> {
    usecase "Register Operative" as opreg
    usecase "Generate Operative" as opgen
    usecase "Manage Operative Data" as opedit
    usecase "List Operatives" as oplist
    usecase "List Operatives History" as ophistory

    usecase "Display Operatives Data" as opdata

    usecase "Decomission Operative" as opretire
    usecase "Re-enlist Operative" as opreenlist

    usecase "Petition Operative" as oppetition
    usecase "Detain Operative" as opdetain
    usecase "Release Operative" as oprelease
}

gm --> foundry : uses
foundry --> api : only on table
discord <--> dcisDiscord : uses
dcisDiscord --> api

operatives -.-> dcisGaming : check table
operatives -.-> dcisUsers : user logs

user --> opreg : self
user --> oplist
user --> opgen : self
user --> opedit : owned
user --> opdata : owned
user --> ophistory : owned
user --> opretire : owned
user --> oppetition
user --> discord : uses

gm --> opdata : on table
gm --> ophistory : on table

api --> oplist
api --> opgen
api --> opedit
api --> opdata
api --> ophistory
api --> opretire
api --> opreenlist
api --> oppetition

oplist <-- orga
opdata <-- orga : any
opedit <-- orga : any
ophistory <-- orga : any
opretire <-- orga : any
opreenlist <-- orga
oppetition <-- orga
oprelease <-- orga
opreg <-- orga : any
opedit <-- orga : any
opdetain <-- orga
@enduml
