[[level1-dcis-threats]]
= Level 1: dcis-threats
(((SCS, dcis-threats)))
(((dcis-threats)))

.The management and use of new ((Threat))s.
[plantuml,business-context-threats,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player as user << Human >>
GM as gm << Human >>
Judge as judge << Human >>
Orga as orga << Human >>
Admin as admin << Human >>

user <|-- gm : is a

:Foundry VTT: as foundryVTT << System >>
:Torg-Codex: as torgCodex << System >>

rectangle Threats {
    usecase "Create a new threat" as cthreat
    usecase "Remove a threat" as cremove

    usecase "Petition threat" as pthreat
    usecase "Block threat" as cblock
    usecase "Unblock threat" as cunblock

    usecase "List existing threats" as clist
    usecase "Download a threat" as cdown
}


user --> clist
user --> cdown
user --> pthreat
user --> cblock : owned
user --> cunblock : self blocked
user --> cthreat
user --> cremove : owned

cthreat <-- orga
clist <-- orga
cdown <-- orga
cblock <-- orga
cunblock <-- orga
pthreat <-- orga
cblock <-- judge
cunblock <-- judge
cremove <-- judge
cthreat <-- admin
cremove <-- admin
clist <-- admin
cdown <-- admin
cblock <-- admin
cunblock <-- admin

foundryVTT --> pthreat
foundryVTT --> clist
foundryVTT --> cdown
torgCodex <.. cdown : asynchronous
torgCodex ..> pthreat : asynchronous
torgCodex <.. cthreat : asynchronous

@enduml
....
