= Level 1: dcis-libraries
(((Libraries))) (((Libraries, discord))) (((Libraries, dcis-lib-users))) (((Libraries, dcis-lib-petitions)))

include::partial$includes/config.adoc[]

These are the libraries with common functionalities for all SCSes.
The libraries are the clients.
They are responsible for the asynchronous data transfer of the data between the systems.
So they will basically receive the data from the leading SCS via messaging and provide a default
handler to retrieve the data. There is a second library for a default JPA implementation to keep the data.
Every SCS has to decide if keeping the default data for the domain is fine or if it needs to implement the handler interface itself.

== Use cases

.Discord Bot.
[plantuml,dcis-libraries-level1,svg]
----
@startuml

skinparam nodesep 50
skinparam ranksep 200

rectangle "Torganized Play Libraries" as torgLibraries {
  [Library Operatives] as libOperatives << Client >>
  [Library Gaming] as libGaming << Client >>
  [Library Threats] as libThreats << Client >>
  [Library Codex] as libCodex << Client >>
}

rectangle "Torganized Play Data Store Libraries" as dataLibraries {
  [Library Operatives Data] as jpaOperatives << DataStore >>
  [Library Gaming Data] as jpaGaming << DataStore >>
  [Library Threats Data] as jpaThreats << DataStore >>
  [Library Codex Data] as jpaCodex << DataStore >>
}

rectangle "Generic Libraries" as genericLibraries {
  [Library Users] as libUsers << Client >>
  [Library Arbitration] as libArbitration << Client >>
}

rectangle "Generic Data Store Libraries" as genericDataLibraries {
  [Library User Data] as jpaUsers << DataStore >>
  [Library Arbitration] as jpaArbitration << DataStore >>
}

rectangle "External Libraries" as externalLibs {
  [kp-commons] as kpCommons << External >>
  [kp-rpg-torg] as kpTorg << External >>
  [kp-rpg] as kpRPG << External >>
  [kp-discord] as kpDiscord << External >>
  [kp-rpg-drivethru] as kpDrivethru << External >>
}


() "dcis-users" as dcisUsers << DCIS >>
() "dcis-operatives" as dcisOperatives << DCIS >>
() "dcis-gaming" as dcisGaming << DCIS >>
() "dcis-threats" as dcisThreats << DCIS >>
() "torg-codex" as codex << DCIS >>
() "dcis-arbitration" as dcisArbitration << DCIS >>
() "Discord" as discord << External >>
() "DriveThru" as drivethru << External >>

libUsers ..> dcisUsers : uses
libUsers -.-> jpaUsers : optional

libOperatives ..> kpTorg : uses
libOperatives ..> dcisOperatives : uses
libOperatives -.-> jpaOperatives : optional

libGaming ..> kpTorg : uses
libGaming ..> dcisGaming : uses
libGaming -.-> jpaGaming : optional

libThreats ..> kpTorg : uses
libThreats ..> dcisThreats : uses
libThreats -.-> jpaThreats : optional

libCodex ..> codex : uses
libCodex ..> kpTorg : uses
libCodex -.-> jpaCodex : optional

libArbitration ..> dcisArbitration : uses
libArbitration -.-> jpaArbitration : optional

kpTorg --> kpRPG
kpDiscord ..> discord : uses
kpDrivethru ..> drivethru : uses
@enduml

----


== Fulfilled Requirements

* {fs01}
* {fs02}
* {fs04}
* {mt01}


== Open Issues/Problems/Risks

It's only an idea yet.

<<<
