[[level1-dcis-operatives]]
= Level 1: dcis-operatives
(((SCS, dcis-operatives)))
(((dcis-operatives)))

.These use cases revolve around the ((PC))s. They are called ((Operative))s here.
[plantuml,business-context-operatives,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player as user << Human >>
GM as gm << Human >>

:Foundry VTT: as foundryVTT << System >>
:DCIS Gaming: as dcisGaming << System >>

Judge as judge << Human >>
Orga as orga << Human >>
Admin as admin << Human >>


rectangle Operatives {
    usecase "Register Operative" as opreg
    usecase "Generate Operative" as opgen
    usecase "Manage Operative Data" as opedit
    usecase "List Operatives" as oplist
    usecase "List Operatives History" as ophistory

    usecase "Display Operatives Data" as opdata

    usecase "Decomission Operative" as opretire
    usecase "Re-enlist Operative" as opreenlist

    usecase "Petition Operative" as oppetition
    usecase "Detain Operative" as opdetain
    usecase "Release Operative" as oprelease
}

gm --> foundryVTT : uses
foundryVTT --> oplist : only on table
foundryVTT --> opdata : only on table
foundryVTT --> ophistory : only on table

oplist ..> dcisGaming : checks table
opdata ..> dcisGaming : checks table
ophistory ..> dcisGaming : checks table

user --> opreg
user --> oplist
user --> opgen
user --> opedit : only owned
user --> opdata : only owned
user --> ophistory : only owned
user --> opretire : only owned
user --> oppetition
gm --> oplist
gm --> opdata : only on table
gm --> ophistory : only on table
gm --> oppetition
oplist <-- judge
opdata <-- judge
opedit <-- judge
ophistory <-- judge
opretire <-- judge
opreenlist <-- judge
opdetain <-- judge
oprelease <-- judge
oplist <-- orga
opdata <-- orga
opedit <-- orga
ophistory <-- orga
opretire <-- orga
opreenlist <-- orga
oppetition <-- orga
oprelease <-- orga
opreg <-- admin
opedit <-- admin
oplist <-- admin
opdata <-- admin
ophistory <-- admin
opretire <-- admin
opreenlist <-- admin
opdetain <-- admin
oprelease <-- admin
@enduml
....
