[[level1-torg-codex]]
= Level 1: torg-codex
(((SCS, torg-codex)))
(((torg-codex)))

.The integrated ((torg-codex)).
[plantuml,business-context-codex,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

Player as user << Human >>
GM as gm << Human >>
Judge as judge << Human >>
Orga as orga << Human >>
Admin as admin << Human >>

:Foundry VTT: as foundryVTT << System >>
:DCIS Threats: as dcisThreats << System >>

user <|-- judge : is a
user <|-- orga : is a
user <|-- admin : is a

rectangle Threats {
    usecase "List Threats" as lthreat
    usecase "Threat Data" as dthreat
    usecase "Create Threat" as cthreat
    usecase "Delete Threat" as rthreat
}

rectangle Items {
    usecase "List Items" as litem
    usecase "Item Data" as ditem
    usecase "Create Item" as citem
    usecase "Delete Item" as ritem
}

rectangle Perks {
    usecase "List Perk" as lperk
    usecase "Perk Data" as dperk
    usecase "Create perk" as cperk
    usecase "Delete perk" as rperk
}

rectangle Powers {
    usecase "List Power" as lpower
    usecase "Power Data" as dpower
    usecase "Create Power" as cpower
    usecase "Delete Power" as rpower
}

rectangle Ownership {
    usecase "Register Owernship" as rowner
    usecase "Unregister Ownership" as downer
}

rectangle Petitions {
    usecase (Petition Content)/ as petition
    usecase (Block Content)/ as block
    usecase (Unblock Content)/ as unblock
    usecase (Delete Content)/ as delete
}

user --> petition
user --> litem : owned or free
user --> ditem : owned or free
user --> citem : owned
user --> ritem : owned
user --> lthreat : owned or free
user --> dthreat : owned or free
user --> lperk : owned or free
user --> dperk : owned or free
user --> cperk : owned
user --> rperk : owned
user --> lpower : owned or free
user --> dpower : owned or free
user --> cpower : owned
user --> rpower : owned
user --> dcisThreats : uses
user <|-- gm : is a
user --> rowner : self
user --> downer : self
gm --> foundryVTT : uses

block <-- admin
unblock <-- admin
delete <-- admin
rowner <-- admin
downer <-- admin

block <-- judge
unblock <-- judge
delete <-- judge
downer <-- judge

delete -.-> ritem
delete -.-> rperk
delete -.-> rpower
delete -.-> dcisThreats : delete

block <-- orga
unblock <-- orga
downer <-- orga

litem <-- foundryVTT : owned or free
ditem <-- foundryVTT : owned or free
lthreat <-- foundryVTT : owned or free
dthreat <-- foundryVTT : owned or free
lperk <-- foundryVTT : owned or free
dperk <-- foundryVTT : owned or free
lpower <-- foundryVTT : owned or free
dpower <-- foundryVTT : owned or free

lthreat ..> dcisThreats : asynchronous
dthreat ..> dcisThreats : asynchronous
cthreat <.. dcisThreats : asynchronous
rthreat <.. dcisThreats : asynchronous

@enduml
....
