= Level 2: dcis-libraries

include::partial$includes/config.adoc[]

(((Libraries)))

[NOTE]
====
Auf Level 2 werden nur die allgemeinen Informationen über die Maven-Struktur und die Packages gegeben.
Für weitere Informationen wird auf die jeweiligen JavaDocs der Bibliotheken verwiesen.
Das Handling der drei verschiedenen Bibliothekstypen wird in xref:08_concepts/asynchronus-data-handling.adoc[] tiefergehend beschrieben.
====


== Client Libraries

=== ((dcis-client-arbitration))
(((Libraries)))(((Libraries, dcis-client-arbitration)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-client-arbitration
| Package | de.paladinsinn.tp.dcis..client
| Handler | de.paladinsinn.tp.dcis.arbitration.client.events.ArbitrationEventsHandler
| Queue (out) | dcis.arbitrations.modification (arbitrations-modification)
| Topics (in) | dcis.arbitrations.changes (arbitrations-changes)
| Application config snippet
| [source,yaml]
----
spring:
  application:
    name: dcis-users
    system: DCIS
  cloud:
    stream:
      # noinspection SpringBootApplicationYaml
      bindings:
        input:
          users-changes:
            destination: dcis.arbitrations.changes
            content-type: application/json
            consumer:
              use-native-decoding: false
              auto-startup: true
        output:
          users-modification:
            destination: dcis.arbitrations.modification
            content-type: application/json
            producer:
              use-native-encoding: false
              auto-startup: true
----
|===


=== ((dcis-client-operatives))
(((Libraries)))(((Libraries, dcis-client-operatives)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-client-operatives
| Package | de.paladinsinn.tp.dcis.operatives.client
| Handler | de.paladinsinn.tp.dcis.operatives.client.events.OperativesEventsHandler
| Queue (out) | dcis.operatives.modification (operatives-modification)
| Topics (in) | dcis.operatives.changes (operatives-changes)
| Application config snippet
| [source,yaml]
----
spring:
  application:
    name: dcis-users
    system: DCIS
  cloud:
    stream:
      # noinspection SpringBootApplicationYaml
      bindings:
        input:
          users-changes:
            destination: dcis.operatives.changes
            content-type: application/json
            consumer:
              use-native-decoding: false
              auto-startup: true
        output:
          users-modification:
            destination: dcis.operatives.modification
            content-type: application/json
            producer:
              use-native-encoding: false
              auto-startup: true
----
|===


=== ((dcis-client-gaming))
(((Libraries)))(((Libraries, dcis-client-gaming)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-client-gaming
| Package | de.paladinsinn.tp.dcis.gaming.client
| Handler | de.paladinsinn.tp.dcis.gaming.client.events.GamingEventsHandler
| Queue (out) | dcis.gaming.modification (gaming-modification)
| Topics (in) | dcis.gaming.changes (gaming-changes)
| Application config snippet
| [source,yaml]
----
spring:
  application:
    name: dcis-users
    system: DCIS
  cloud:
    stream:
      # noinspection SpringBootApplicationYaml
      bindings:
        input:
          users-changes:
            destination: dcis.gaming.changes
            content-type: application/json
            consumer:
              use-native-decoding: false
              auto-startup: true
        output:
          users-modification:
            destination: dcis.gaming.modification
            content-type: application/json
            producer:
              use-native-encoding: false
              auto-startup: true
----
|===


=== ((dcis-client-threats))
(((Libraries)))(((Libraries, dcis-client-threats)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-client-threats
| Package | de.paladinsinn.tp.dcis.threats.client
| Handler | de.paladinsinn.tp.dcis.threats.client.events.ThreatEventsHandler
| Queue (out) | dcis.threats.modification (threats-modification)
| Topics (in) | dcis.threats.changes (threats-changes)
| Application config snippet
| [source,yaml]
----
spring:
  application:
    name: dcis-users
    system: DCIS
  cloud:
    stream:
      # noinspection SpringBootApplicationYaml
      bindings:
        input:
          users-changes:
            destination: dcis.threats.changes
            content-type: application/json
            consumer:
              use-native-decoding: false
              auto-startup: true
        output:
          users-modification:
            destination: dcis.threats.modification
            content-type: application/json
            producer:
              use-native-encoding: false
              auto-startup: true
----
|===


=== ((dcis-client-codex))
(((Libraries)))(((Libraries, dcis-client-codex)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-client-codex
| Package | de.paladinsinn.tp.dcis.codex.client
| Handler | de.paladinsinn.tp.dcis.codex.client.events.CodexEventsHandler
| Queue (out) | dcis.codex.modification (codex-modification)
| Topics (in) | dcis.codex.changes (codex-changes)
| Application config snippet
| [source,yaml]
----
spring:
  application:
    name: dcis-users
    system: DCIS
  cloud:
    stream:
      # noinspection SpringBootApplicationYaml
      bindings:
        input:
          users-changes:
            destination: dcis.codex.changes
            content-type: application/json
            consumer:
              use-native-decoding: false
              auto-startup: true
        output:
          users-modification:
            destination: dcis.codex.modification
            content-type: application/json
            producer:
              use-native-encoding: false
              auto-startup: true
----
|===


=== ((dcis-client-discord))
(((Libraries)))(((Libraries, dcis-client-discord)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-client-discord
| Package | de.paladinsinn.tp.dcis.discord.client
| Handler | de.paladinsinn.tp.dcis.discord.client.events.EventsHandler
| Queue (out) | dcis.discord.output (discord-modification)
| Topics (in) | dcis.discord.input (discord-changes)
| Application config snippet
| [source,yaml]
----
spring:
  application:
    name: dcis-users
    system: DCIS
  cloud:
    stream:
      # noinspection SpringBootApplicationYaml
      bindings:
        input:
          users-changes:
            destination: dcis.discord.changes
            content-type: application/json
            consumer:
              use-native-decoding: false
              auto-startup: true
        output:
          users-modification:
            destination: dcis.discord.modification
            content-type: application/json
            producer:
              use-native-encoding: false
              auto-startup: true
----
|===


== Store Libraries

=== Application config snippet

The snippet presented points to a file mode H2 database in PostgreSQL mode.
The `url`, `username` and `password` will be overwritten via environment variables during runtime:

* `SPRING_DATASOURCE_URL`
* `SPRING_DATASOURCE_USERNAME`
* `SPRING_DATASOURCE_PASSWORD`

.Default snippet for `application.yml` for datase setup.
[source,yaml]
----
spring:
  datasource:
    url: jdbc:h2:file:./target/db;MODE=PostgreSQL
    username: sa
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    showSql: false
    hibernate:
      ddlAuto: validate

  liquibase:
    enabled: true
    show-summary-output: log
    show-summary: summary
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
----


=== ((dcis-store-arbitration))
(((Libraries)))(((Libraries, dcis-store-arbitration)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-store-arbitration
| Package | de.paladinsinn.tp.dcis.arbitration.store
| Changelog | db/arbitration/master.yml
|===


=== ((dcis-store-operatives))
(((Libraries)))(((Libraries, dcis-store-operatives)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-store-operatives
| Package | de.paladinsinn.tp.dcis.operatives.store
| Changelog | db/operatives/master.yml
|===


=== ((dcis-store-gaming))
(((Libraries)))(((Libraries, dcis-store-gaming)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-store-gaming
| Package | de.paladinsinn.tp.dcis.gaming.store
| Changelog | db/gaming/master.yml
|===


=== ((dcis-store-threats))
(((Libraries)))(((Libraries, dcis-store-threats)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-store-threats
| Package | de.paladinsinn.tp.dcis.threats.store
| Changelog | db/threats/master.yml
|===


=== ((dcis-store-codex))
(((Libraries)))(((Libraries, dcis-store-codex)))

[cols="<.<5,<.<15a", frame="topbot", grid="rows"]
|===
| GroupId | de.paladins-inn.torganized-play
| ArtifactId | dcis-store-codex
| Package | de.paladinsinn.tp.dcis.codex.store
| Changelog | db/codex/master.yml
|===

<<<
