ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


=== Business Context

.These use cases revolve around the ((PC))s. They are called ((Operative))s here.
[plantuml,business-context-operatives,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome

actor Player as player
actor GM as gm


rectangle Operatives {
    usecase "Register Operative" as opreg
    usecase "List Operatives" as oplist
    usecase "List Operatives History" as ophistory
    usecase "Retire Operative" as opretire
}

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

player --> opreg
player --> oplist
player --> ophistory
player --> opretire
gm --> oplist
gm --> ophistory
judge --> oplist
judge --> ophistory
judge --> opretire
orga --> oplist
orga --> ophistory
orga --> opretire
admin --> opreg
admin --> oplist
admin --> ophistory
admin --> opretire

@enduml
....

.These use cases revolve around the session (((Session)) management of the games and the shared campaign (((Shared Campaign))) management.
[plantuml,business-context-gaming,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Gaming {
    usecase "Create new Mission" as mcreate

    usecase "Register new Mission" as mreg
    usecase "Score a played Mission" as mscore

    usecase "Score a played Special Mission" as smscore

    usecase "List open Missions" as mlist
    usecase "Apply for Mission" as mapply
    usecase "Accept for Mission" as maccept
    usecase "Remove Operative from Mission" as mremove
}

player --> mlist
player --> mapply
gm --> mreg
gm --> mscore
gm --> smscore
gm --> mlist
gm --> maccept
gm --> mremove
judge --> mlist
judge --> mremove
orga --> mcreate
orga --> mlist
orga --> mremove
admin --> mcreate
admin --> mreg
admin --> mscore
admin --> smscore
admin --> mlist
admin --> mapply
admin --> maccept
admin --> mremove

@enduml
....


.The management and use of new ((Trheat))s.
[plantuml,business-context-threats,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Threats {
    usecase "Create a new Threat" as cthreat
    usecase "Remove one of my threats" as cremove

    usecase "List existing Threats" as clist
    usecase "Download selected Threat" as cdown
}

gm --> cthreat
gm --> cremove
gm --> clist
gm --> cdown
orga --> cthreat
orga --> cremove
orga --> clist
orga --> cdown
admin --> cthreat
admin --> cremove
admin --> clist
admin --> cdown

@enduml
....


.The integrated ((torg-codex)).
[plantuml,business-context-codex,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Codex {
    usecase "All of torg-codex" as codex
}

player --> codex

@enduml
....


.Player management.
[plantuml,business-context-player,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Player {
    usecase "List players" as ulist
    usecase "List player logfile" as ulogfile

    usecase "Create new logfile entry" as ulog
}

player --> ulist
player --> ulogfile
gm --> ulist
judge --> ulist
judge --> ulogfile
orga --> ulist
orga --> ulogfile
admin --> ulist
admin --> ulogfile

@enduml
....


=== Technical Context

.The technical context of the DCIS.
[plantuml,technical-context,svg]
....
@startuml
@startuml
skinparam actorStyle awesome

actor :Player:
actor :GM:
actor :Judge:
actor :Orga:
actor :Admin:

[k8s ingress]
component "k8s ingress" {
    portin HTTP as HTTPingressIn

    component "ingress" as HTTPingress

    HTTPingressIn -- HTTPingress
}

[FoundryVTT]
[SSO]

together{
    [dcis-gaming]
    [torg-codex]
    [dcis-threats]
    [dcis-operatives]
    together {
        [dcis-players]
        [mail]
        [discord]
    }
}
[dcis-commons]

component dcis-gaming {
    portin HTTP as HTTPgaming
    portout kafka as KAFKAgaming

    component "torganized-play-gaming" as DCISgaming
    database "PostgreSQL" as gamingDB

    HTTPgaming -- DCISgaming
    KAFKAgaming -- DCISgaming
    DCISgaming -- gamingDB
}

component torg-codex {
    portin HTTP as HTTPcodex
    portout kafka as KAFKAcodex

    component "torg-codex" as DCIScodex
    database "MongoDB" as codexDB

    HTTPcodex -- DCIScodex
    KAFKAcodex -- DCIScodex
    DCIScodex -- codexDB
}

component dcis-threats {
    portin HTTP as HTTPthreats
    portout kafka as KAFKAthreats

    component "torganized-play-threats" as DCISthreats
    database "PostgreSQL" as threatsDB

    HTTPthreats -- DCISthreats
    KAFKAthreats -- DCISthreats
    DCISthreats -- threatsDB
}

[kafka-broker]
component "kafka-broker" {
    portin kafka as KAFKAbroker

    component "kafka-broker" as DCISkafka

    KAFKAbroker -- DCISkafka
}

component dcis-operatives {
    portin HTTP as HTTPoperatives
    portout kafka as KAFKAoperatives

    component "torganized-play-operatives" as DCISoperatives
    database "PostgreSQL" as operativesDB

    HTTPoperatives -- DCISoperatives
    KAFKAoperatives -- DCISoperatives
    DCISoperatives -- operativesDB
}

component dcis-players {
    portin HTTP as HTTPplayers
    portout kafka as KAFKAplayers

    component "torganized-play-players" as DCISplayers
    database "PostgreSQL" as playersDB

    HTTPplayers -- DCISplayers
    KAFKAplayers -- DCISplayers
    DCISplayers -- playersDB
}

component dcis-commons {
    portin HTTP as HTTPcommons

    component "torganized-play-commons" as DCIScommons

    HTTPcommons -- DCIScommons
}



:Player: .d.> HTTPingressIn
:GM: .d.> HTTPingressIn
:Judge: .d.> HTTPingressIn
:Orga: .d.> HTTPingressIn
:Admin: .d.> HTTPingressIn

FoundryVTT .d.> HTTPingressIn

DCISgaming ..> SSO
DCIScodex ..> SSO
DCISthreats ..> SSO
DCISoperatives ..> SSO
DCISplayers ..> SSO

HTTPingress .d.> HTTPgaming : use
HTTPingress .d.> HTTPcodex : use
HTTPingress .d.> HTTPthreats : use
HTTPingress .d.> HTTPoperatives : use
HTTPingress .d.> HTTPplayers : use
HTTPingress .d.> HTTPcommons : use

DCISplayers ..> mail : use
DCISplayers ..> discord : use

KAFKAbroker <.u.> KAFKAgaming : use
KAFKAbroker <.u.> KAFKAcodex : use
KAFKAbroker <.u.> KAFKAthreats : use
KAFKAbroker <.u.> KAFKAoperatives : use
KAFKAbroker <.u.> KAFKAplayers : use
@enduml
....

**<Mapping Input/Output to Channels>**
