= System Scope and Context
[[section-system-scope-and-context]]

ifndef::imagesdir[:imagesdir: ../images]


== Business Context

.These use cases revolve around the ((PC))s. They are called ((Operative))s here.
[plantuml,business-context-operatives,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

actor Player as player
actor GM as gm


rectangle Operatives {
    usecase "Register Operative" as opreg
    usecase "List Operatives" as oplist
    usecase "List Operatives History" as ophistory
    usecase "Decomission Operative" as opretire
    usecase "Re-enlist Operative" as opreenlist
}

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

player --> opreg
player --> oplist
player --> ophistory
player --> opretire
gm --> oplist
gm --> ophistory
judge --> oplist
judge --> ophistory
judge --> opretire
judge --> opreenlist
orga --> oplist
orga --> ophistory
orga --> opretire
orga --> opreenlist
admin --> opreg
admin --> oplist
admin --> ophistory
admin --> opretire
admin --> opreenlist

@enduml
....

.These use cases revolve around the session (((Session)) management of the games and the shared campaign (((Shared Campaign))) management.
[plantuml,business-context-gaming,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Gaming {
    usecase "Create new Mission" as mcreate

    usecase "Register new Mission" as mreg
    usecase "Score a played Mission" as mscore

    usecase "Score a played Special Mission" as smscore

    usecase "List open Missions" as mlist
    usecase "Apply for Mission" as mapply
    usecase "Accept for Mission" as maccept
    usecase "Remove Operative from Mission" as mremove
}

player --> mlist
player --> mapply
player --> mremove
gm --> mreg
gm --> mscore
gm --> smscore
gm --> mlist
gm --> maccept
gm --> mremove
judge --> mlist
judge --> mremove
orga --> mcreate
orga --> mlist
orga --> mremove
admin --> mcreate
admin --> mreg
admin --> mscore
admin --> smscore
admin --> mlist
admin --> mapply
admin --> maccept
admin --> mremove

@enduml
....


.The management and use of new ((Trheat))s.
[plantuml,business-context-threats,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Threats {
    usecase "Create a new Threat" as cthreat
    usecase "Remove one of my threats" as cremove

    usecase "List existing Threats" as clist
    usecase "Download selected Threat" as cdown
}

gm --> cthreat
gm --> cremove
gm --> clist
gm --> cdown
orga --> cthreat
orga --> cremove
orga --> clist
orga --> cdown
admin --> cthreat
admin --> cremove
admin --> clist
admin --> cdown

@enduml
....


.The integrated ((torg-codex)).
[plantuml,business-context-codex,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Codex {
    usecase "All of torg-codex" as codex
}

player --> codex

@enduml
....


.Player management.
[plantuml,business-context-player,svg]
....
@startuml
left to right direction
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

actor Player as player
actor GM as gm

rectangle TorganizedPlay {
    actor Judge as judge
    actor Orga as orga
    actor Admin as admin
}

rectangle Player {
    usecase "List players" as ulist
    usecase "List player logfile" as ulogfile

    usecase "Create new logfile entry" as ulog

    usecase "Detain player" as udetain
    usecase "Petition Detainment" as udetainpetition
    usecase "Release player" as urelease

    usecase "Ban player" as uban
    usecase "Petition Ban" as ubanpetition
    usecase "Unban player" as uunban
}

player --> ulist
player --> ulogfile
player --> udetainpetition
player --> ubanpetition
gm --> ulist
judge --> ulist
judge --> ulogfile
judge --> uban
judge --> uunban
judge --> udetain
judge --> urelease
orga --> ulist
orga --> ulogfile
orga --> udetain
orga --> urelease
orga --> udetainpetition
admin --> ulist
admin --> ulogfile
admin --> uban
admin --> uunban
admin --> udetain
admin --> urelease

@enduml
....


<<<
== Technical Context

.The technical context of the DCIS.
[plantuml,technical-context,svg]
....
@startuml
skinparam actorStyle awesome
skinparam nodesep 50
skinparam ranksep 200

actor :Player:
actor :GM:
actor :Judge:
actor :Orga:
actor :Admin:

[k8s ingress]
component "k8s ingress" {
    portin HTTP as HTTPingressIn

    component "ingress" as HTTPingress

    HTTPingressIn -- HTTPingress
}

[FoundryVTT]
[SSO]

together{
    [dcis-gaming]
    [torg-codex]
    [dcis-threats]
    [dcis-operatives]
    together {
        [dcis-players]
        [mail]
        [discord]
    }
}
[dcis-commons]

component dcis-gaming {
    portin HTTP as HTTPgaming
    portout broker as BROKERgaming

    component "torganized-play-gaming" as DCISgaming
    database "PostgreSQL" as gamingDB

    HTTPgaming -- DCISgaming
    BROKERgaming -- DCISgaming
    DCISgaming -- gamingDB
}

component torg-codex {
    portin HTTP as HTTPcodex
    portout broker as BROKERcodex

    component "torg-codex" as DCIScodex
    database "MongoDB" as codexDB

    HTTPcodex -- DCIScodex
    BROKERcodex -- DCIScodex
    DCIScodex -- codexDB
}

component dcis-threats {
    portin HTTP as HTTPthreats
    portout broker as BROKERthreats

    component "torganized-play-threats" as DCISthreats
    database "PostgreSQL" as threatsDB

    HTTPthreats -- DCISthreats
    BROKERthreats -- DCISthreats
    DCISthreats -- threatsDB
}

[broker-broker]
component "broker-broker" {
    portin broker as BROKERbroker

    component "broker-broker" as DCISbroker

    BROKERbroker -- DCISbroker
}

component dcis-operatives {
    portin HTTP as HTTPoperatives
    portout broker as BROKERoperatives

    component "torganized-play-operatives" as DCISoperatives
    database "PostgreSQL" as operativesDB

    HTTPoperatives -- DCISoperatives
    BROKERoperatives -- DCISoperatives
    DCISoperatives -- operativesDB
}

component dcis-players {
    portin HTTP as HTTPplayers
    portout broker as BROKERplayers

    component "torganized-play-players" as DCISplayers
    database "PostgreSQL" as playersDB

    HTTPplayers -- DCISplayers
    BROKERplayers -- DCISplayers
    DCISplayers -- playersDB
}

component dcis-commons {
    portin HTTP as HTTPcommons

    component "torganized-play-commons" as DCIScommons

    HTTPcommons -- DCIScommons
}



:Player: .d.> HTTPingressIn
:GM: .d.> HTTPingressIn
:Judge: .d.> HTTPingressIn
:Orga: .d.> HTTPingressIn
:Admin: .d.> HTTPingressIn

FoundryVTT .d.> HTTPingressIn

DCISgaming ..> SSO
DCIScodex ..> SSO
DCISthreats ..> SSO
DCISoperatives ..> SSO
DCISplayers ..> SSO

HTTPingress .d.> HTTPgaming : use
HTTPingress .d.> HTTPcodex : use
HTTPingress .d.> HTTPthreats : use
HTTPingress .d.> HTTPoperatives : use
HTTPingress .d.> HTTPplayers : use
HTTPingress .d.> HTTPcommons : use

DCISplayers ..> mail : use
DCISplayers ..> discord : use

BROKERbroker <.u.> BROKERgaming : use
BROKERbroker <.u.> BROKERcodex : use
BROKERbroker <.u.> BROKERthreats : use
BROKERbroker <.u.> BROKERoperatives : use
BROKERbroker <.u.> BROKERplayers : use
@enduml
....

**<Mapping Input/Output to Channels>**
