[[business-context]]
= Business Context

.The business context of the DCIS.
[plantuml,business-context,svg]
....
@startuml
skinparam actorStyle awesome

together {
  :GM: as gm << Human >>
  :Judge: as judge << Human >>
  :Orga: as orga << Human >>
  :Admin: as admin << Human >>

  together {
    :Player: as player << Human >>

    rectangle <<External>> {
      :Foundry VTT: as foundry << System >>
      :Discord: as discord << System >>
      :Mail Server: as mail << System >>
    }
  }
}


gm    .d.|> player : is a
judge .d.|> player : is a
orga  .d.|> player : is a
admin .d.|> player : is a

together {
  rectangle << Virtual >> {
    :UI Layer: as ui
    :API Layer: as api
  }
}

together {
  rectangle {
    :DCIS Users: as users << System >>
    :DCIS Arbitration: as arbitration << System >>
  }

  rectangle {
    :DCIS Operatives: as operatives << System >>
  }

  rectangle {
    :DCIS Gaming: as gaming << System >>
  }

  rectangle {
    :DCIS Threats: as threats << System >>
  }

  rectangle {
    :Torg Codex: as codex << System >>
  }

  rectangle {
    :Single Sign-On: as sso << System >>
  }

  rectangle {
    :Discord Bot: as bot << System >>
  }
}


ui --> users
ui --> arbitration
ui --> operatives
ui --> gaming
ui --> threats
ui --> codex

player --> ui
player --> foundry
gm --> foundry
admin --> sso

foundry --> api
discord <--> bot

users <-- bot
arbitration <-- bot
operatives <-- bot
gaming <-- bot
threats <-- bot
codex <-- bot


api --> users
api --> arbitration
api --> operatives
api --> gaming
api --> threats
api --> codex

users ..> sso
arbitration ..> sso
operatives ..> sso
gaming ..> sso
threats ..> sso
codex ..> sso

users .-.> mail
users .-.> discord
@enduml
....